### ISSUE TITLE
将demo中的kotlin转换为java后设置颜色片段无效

### ISSUE THREAD

**Issue by ChesterChai** [Liberations/TimeRuler#3]
`
package com.kubi.timruledemo;

import android.os.Bundle;
import androidx.appcompat.app.AppCompatActivity;

import com.kubi.timeruler.TimeRulerBar;

import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;

public class MainActivity extends AppCompatActivity {
    
    TimeRulerBar time_scale_view;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        time_scale_view = findViewById(R.id.timeBar);

        //初始化时间轴时间范围，缩放模式，设置回调
        Calendar time_scale_range_calendar = Calendar.getInstance();
        time_scale_range_calendar.set(2021,1,1,0,0,0);
        long time_scale_range_starttime = time_scale_range_calendar.getTimeInMillis();
        time_scale_range_calendar.set(2021,1,1,23,59,59);
        long time_scale_range_endtime = time_scale_range_calendar.getTimeInMillis();

        time_scale_view.setRange(time_scale_range_starttime, time_scale_range_endtime);
        time_scale_view.setMode(TimeRulerBar.MODE_UINT_30_MIN);

        List<VideoBean> videos = new ArrayList<>();
        long testTime = System.currentTimeMillis();
        for (int i = 1; i < 6; i++) {
            VideoBean video = new VideoBean(testTime, testTime + i * 10 * 60 * 1000, false);
            videos.add(video);
            testTime += i * 15 * 60 * 1000;
        }
        TimeBean timeBean = new TimeBean(videos);
        time_scale_view.setColorScale(timeBean);

        time_scale_view.setCursorValue(System.currentTimeMillis());
    }
}}
`
java代码如上所示

**Comment by yuekong** [comment]
> `
> package com.kubi.timruledemo;
> 
> import android.os.Bundle;
> import androidx.appcompat.app.AppCompatActivity;
> 
> import com.kubi.timeruler.TimeRulerBar;
> 
> import java.util.ArrayList;
> import java.util.Calendar;
> import java.util.List;
> 
> public class MainActivity extends AppCompatActivity {
> 
> ```
> TimeRulerBar time_scale_view;
> 
> @Override
> protected void onCreate(Bundle savedInstanceState) {
>     super.onCreate(savedInstanceState);
>     setContentView(R.layout.activity_main);
> 
>     time_scale_view = findViewById(R.id.timeBar);
> 
>     //初始化时间轴时间范围，缩放模式，设置回调
>     Calendar time_scale_range_calendar = Calendar.getInstance();
>     time_scale_range_calendar.set(2021,1,1,0,0,0);
>     long time_scale_range_starttime = time_scale_range_calendar.getTimeInMillis();
>     time_scale_range_calendar.set(2021,1,1,23,59,59);
>     long time_scale_range_endtime = time_scale_range_calendar.getTimeInMillis();
> 
>     time_scale_view.setRange(time_scale_range_starttime, time_scale_range_endtime);
>     time_scale_view.setMode(TimeRulerBar.MODE_UINT_30_MIN);
> 
>     List<VideoBean> videos = new ArrayList<>();
>     long testTime = System.currentTimeMillis();
>     for (int i = 1; i < 6; i++) {
>         VideoBean video = new VideoBean(testTime, testTime + i * 10 * 60 * 1000, false);
>         videos.add(video);
>         testTime += i * 15 * 60 * 1000;
>     }
>     TimeBean timeBean = new TimeBean(videos);
>     time_scale_view.setColorScale(timeBean);
> 
>     time_scale_view.setCursorValue(System.currentTimeMillis());
> }
> ```
> 
> }}
> `
> java代码如上所示

我也遇到同样的问题，不知道如何解决。

**Comment by Liberations** [comment]
暂时只支持一天的滑动 testTime传的有问题 应该是 time_scale_range_calendar.getTimeInMillis()

**Comment by Liberations** [comment]
` //初始化时间轴时间范围，缩放模式，设置回调
        Calendar time_scale_range_calendar = Calendar.getInstance();
        time_scale_range_calendar.set(2021,1,1,0,0,0);
        long time_scale_range_starttime = time_scale_range_calendar.getTimeInMillis();
        time_scale_range_calendar.set(2021,1,1,23,59,59);
        long time_scale_range_endtime = time_scale_range_calendar.getTimeInMillis();

        time_scale_view.setRange(time_scale_range_starttime, time_scale_range_endtime);
        time_scale_view.setMode(TimeRulerBar.MODE_UINT_30_MIN);

        List<VideoBean> videos = new ArrayList<>();
        for (int i = 1; i < 6; i++) {
            VideoBean video = new VideoBean(time_scale_range_starttime, time_scale_range_starttime + i * 10 * 60 * 1000, false);
            videos.add(video);
            time_scale_range_starttime += i * 15 * 60 * 1000;
        }
        TimeBean timeBean = new TimeBean(videos);
        time_scale_view.setColorScale(timeBean);

        time_scale_view.setCursorValue(time_scale_range_starttime);`
